export type ButtonBehaviorManifestEntry = {
  id: string
  view: "QuickLaunch" | "TaskCenter" | "FlowWorkshop" | "CommandGrid" | "HelpTour" | "Params"
  selector: string
  owner_suite:
    | "critical-buttons"
    | "first-use"
    | "command-grid"
    | "task-center"
    | "flow-workshop"
    | "params"
    | "help-tour"
    | "nonstub"
  criticality: "critical" | "high" | "medium"
  expected_effect: string
  assertion_type:
    | "aria-selected"
    | "visibility-toggle"
    | "text-visible"
    | "toast-visible"
    | "attribute-change"
    | "storage-change"
  case_id: string
}

export const BUTTON_BEHAVIOR_MANIFEST = [
  {
    id: "nav-tab-quick-launch",
    view: "QuickLaunch",
    selector: "data-testid=console-tab-quick-launch",
    owner_suite: "first-use",
    criticality: "critical",
    expected_effect: "切换到快速启动视图并激活对应主导航标签。",
    assertion_type: "aria-selected",
    case_id: "nav-quick-launch-selected",
  },
  {
    id: "nav-tab-task-center",
    view: "TaskCenter",
    selector: "data-testid=console-tab-task-center",
    owner_suite: "task-center",
    criticality: "critical",
    expected_effect: "切换到任务中心视图并显示任务中心面板。",
    assertion_type: "aria-selected",
    case_id: "nav-task-center-selected",
  },
  {
    id: "nav-tab-flow-workshop",
    view: "FlowWorkshop",
    selector: "data-testid=console-tab-flow-draft",
    owner_suite: "flow-workshop",
    criticality: "high",
    expected_effect: "切换到流程工坊视图并显示工坊主卡片。",
    assertion_type: "aria-selected",
    case_id: "nav-flow-workshop-selected",
  },
  {
    id: "taskcenter-tab-command-runs",
    view: "TaskCenter",
    selector: "data-testid=task-center-tab-command-runs",
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "显示命令运行记录 panel 并隐藏模板运行记录 panel。",
    assertion_type: "visibility-toggle",
    case_id: "taskcenter-command-runs-visible",
  },
  {
    id: "taskcenter-tab-template-runs",
    view: "TaskCenter",
    selector: "data-testid=task-center-tab-template-runs",
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "显示模板运行记录 panel 并隐藏命令运行记录 panel。",
    assertion_type: "visibility-toggle",
    case_id: "taskcenter-template-runs-visible",
  },
  {
    id: "quicklaunch-first-use-start-step",
    view: "QuickLaunch",
    selector: "data-testid=quick-launch-first-use-start",
    owner_suite: "first-use",
    criticality: "high",
    expected_effect: "首用引导从 welcome 进入 configure 阶段。",
    assertion_type: "text-visible",
    case_id: "quicklaunch-first-use-start-stage",
  },
  {
    id: "quicklaunch-first-use-locate-config",
    view: "QuickLaunch",
    selector: "data-testid=quick-launch-first-use-locate-config",
    owner_suite: "first-use",
    criticality: "high",
    expected_effect: "首用引导可从任意阶段回到参数配置步骤。",
    assertion_type: "text-visible",
    case_id: "quicklaunch-first-use-locate-config",
  },
  {
    id: "quicklaunch-enter-run-step",
    view: "QuickLaunch",
    selector: 'role=button[name="我已配置，进入运行"]',
    owner_suite: "first-use",
    criticality: "high",
    expected_effect: "首用引导进入 run 阶段，显示运行步骤说明。",
    assertion_type: "text-visible",
    case_id: "quicklaunch-enter-run-stage",
  },
  {
    id: "quicklaunch-sidebar-toggle",
    view: "QuickLaunch",
    selector: "aria-label=收起参数面板",
    owner_suite: "first-use",
    criticality: "medium",
    expected_effect: "参数面板折叠/展开状态切换。",
    assertion_type: "visibility-toggle",
    case_id: "quicklaunch-sidebar-toggle-panel",
  },
  {
    id: "commandgrid-category-frontend",
    view: "CommandGrid",
    selector: "data-testid=command-category-frontend",
    owner_suite: "command-grid",
    criticality: "high",
    expected_effect: "命令卡片列表筛选为前端分类。",
    assertion_type: "text-visible",
    case_id: "commandgrid-filter-frontend",
  },
  {
    id: "commandgrid-category-maintenance",
    view: "CommandGrid",
    selector: "data-testid=command-category-maintenance",
    owner_suite: "command-grid",
    criticality: "high",
    expected_effect: "命令卡片列表筛选为维护分类。",
    assertion_type: "text-visible",
    case_id: "commandgrid-filter-maintenance",
  },
  {
    id: "commandgrid-category-pipeline",
    view: "CommandGrid",
    selector: 'role=tab[name^="流水线"]',
    owner_suite: "command-grid",
    criticality: "high",
    expected_effect: "命令卡片列表筛选为流水线分类。",
    assertion_type: "text-visible",
    case_id: "commandgrid-filter-pipeline",
  },
  {
    id: "taskcenter-refresh-template-runs",
    view: "TaskCenter",
    selector: "data-testid=task-center-template-runs-refresh",
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "模板运行记录面板触发刷新请求。",
    assertion_type: "toast-visible",
    case_id: "taskcenter-refresh-template-runs",
  },
  {
    id: "commandgrid-run-command",
    view: "CommandGrid",
    selector: 'role=button[name="执行"]',
    owner_suite: "command-grid",
    criticality: "critical",
    expected_effect: "触发命令执行 API 并显示提交成功提示。",
    assertion_type: "toast-visible",
    case_id: "commandgrid-run-command-success",
  },
  {
    id: "flowworkshop-save-draft",
    view: "FlowWorkshop",
    selector: 'role=button[name="保存草稿"]',
    owner_suite: "flow-workshop",
    criticality: "high",
    expected_effect: "触发流程草稿保存并显示成功提示。",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-save-draft-success",
  },
  {
    id: "flowworkshop-replay-latest",
    view: "FlowWorkshop",
    selector: 'role=button[name="回放最新流程"]',
    owner_suite: "flow-workshop",
    criticality: "critical",
    expected_effect: "触发最新流程回放并显示成功提示。",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-replay-latest-success",
  },
  {
    id: "flowworkshop-replay-step",
    view: "FlowWorkshop",
    selector: 'role=button[name="试跑"]',
    owner_suite: "flow-workshop",
    criticality: "high",
    expected_effect: "触发单步试跑并显示步骤回放提示。",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-replay-step-success",
  },
  {
    id: "flowworkshop-replay-from-step",
    view: "FlowWorkshop",
    selector: 'role=button[name="续跑"]',
    owner_suite: "flow-workshop",
    criticality: "high",
    expected_effect: "从指定步骤继续回放并显示续跑提示。",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-replay-from-step-success",
  },
  {
    id: "taskcenter-submit-waiting-input",
    view: "TaskCenter",
    selector: 'role=button[name="提交"]',
    owner_suite: "task-center",
    criticality: "high",
    expected_effect: "模板运行等待输入时提交补充信息并继续执行。",
    assertion_type: "toast-visible",
    case_id: "taskcenter-submit-waiting-input-success",
  },
  {
    id: "helptour-open-panel",
    view: "HelpTour",
    selector: "aria-label=帮助",
    owner_suite: "help-tour",
    criticality: "medium",
    expected_effect: "打开帮助面板并展示当前视图帮助信息。",
    assertion_type: "text-visible",
    case_id: "helptour-open-panel",
  },
  {
    id: "helptour-restart-onboarding",
    view: "HelpTour",
    selector: "data-testid=help-panel-restart-onboarding",
    owner_suite: "help-tour",
    criticality: "medium",
    expected_effect: "重置 onboarding 状态并弹出引导浮层。",
    assertion_type: "storage-change",
    case_id: "helptour-restart-onboarding",
  },
  {
    id: "params-base-url-input",
    view: "Params",
    selector: "data-testid=param-base-url-input",
    owner_suite: "params",
    criticality: "high",
    expected_effect: "UIQ_BASE_URL 输入可稳定更新并驱动运行配置。",
    assertion_type: "attribute-change",
    case_id: "params-base-url-input",
  },
  {
    id: "params-toggle-register-password-visibility",
    view: "Params",
    selector: "data-testid=params-toggle-register-password-visibility",
    owner_suite: "params",
    criticality: "medium",
    expected_effect: "注册密码输入框在 password/text 之间切换。",
    assertion_type: "attribute-change",
    case_id: "params-toggle-register-password-visibility",
  },
  {
    id: "params-toggle-api-key-visibility",
    view: "Params",
    selector: "data-testid=params-toggle-api-key-visibility",
    owner_suite: "params",
    criticality: "medium",
    expected_effect: "Gemini API Key 输入框在 password/text 之间切换。",
    assertion_type: "attribute-change",
    case_id: "params-toggle-api-key-visibility",
  },
  {
    id: "params-toggle-token-visibility",
    view: "Params",
    selector: "data-testid=params-toggle-token-visibility",
    owner_suite: "params",
    criticality: "medium",
    expected_effect: "API Token 输入框在 password/text 之间切换。",
    assertion_type: "attribute-change",
    case_id: "params-toggle-token-visibility",
  },
] as const satisfies readonly ButtonBehaviorManifestEntry[]
