// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.

import { requestJson } from "../core/request";



export async function getCsrfToken(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/csrf`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function postRegisterUser(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/register`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function listAutomationCommands(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/automation/commands`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function listAutomationTasks(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/automation/tasks`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function getAutomationTask(baseUrl: string, pathParams: { task_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/automation/tasks/${encodeURIComponent(pathParams.task_id)}`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function runAutomationCommand(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/automation/run`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function cancelAutomationTask(baseUrl: string, pathParams: { task_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/automation/tasks/${encodeURIComponent(pathParams.task_id)}/cancel`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function createComputerUseSession(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/computer-use/sessions`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function previewComputerUseAction(baseUrl: string, pathParams: { session_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/computer-use/sessions/${encodeURIComponent(pathParams.session_id)}/preview`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function confirmComputerUseAction(baseUrl: string, pathParams: { session_id: string; action_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/computer-use/sessions/${encodeURIComponent(pathParams.session_id)}/confirm/${encodeURIComponent(pathParams.action_id)}`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function executeComputerUseAction(baseUrl: string, pathParams: { session_id: string; action_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/computer-use/sessions/${encodeURIComponent(pathParams.session_id)}/execute/${encodeURIComponent(pathParams.action_id)}`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function readComputerUseEvidence(baseUrl: string, pathParams: { session_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/computer-use/sessions/${encodeURIComponent(pathParams.session_id)}/evidence`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function createBatchEmbeddings(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/embeddings/batch`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function listSessions(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/sessions`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function startSession(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/sessions/start`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function finishSession(baseUrl: string, pathParams: { session_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/sessions/${encodeURIComponent(pathParams.session_id)}/finish`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function listFlows(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/flows`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function createFlow(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/flows`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function importLatestFlow(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/flows/import-latest`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function getFlow(baseUrl: string, pathParams: { flow_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/flows/${encodeURIComponent(pathParams.flow_id)}`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function patchFlow(baseUrl: string, pathParams: { flow_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/flows/${encodeURIComponent(pathParams.flow_id)}`;
  return requestJson(baseUrl, path, "PATCH", init);
}

export async function listTemplates(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/templates`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function createTemplate(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/templates`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function postTemplatesFromArtifacts(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/templates/from-artifacts`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function getTemplate(baseUrl: string, pathParams: { template_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/templates/${encodeURIComponent(pathParams.template_id)}`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function patchTemplate(baseUrl: string, pathParams: { template_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/templates/${encodeURIComponent(pathParams.template_id)}`;
  return requestJson(baseUrl, path, "PATCH", init);
}

export async function exportTemplate(baseUrl: string, pathParams: { template_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/templates/${encodeURIComponent(pathParams.template_id)}/export`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function resolveProfile(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/profiles/resolve`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function previewReconstruction(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/reconstruction/preview`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function generateReconstruction(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/reconstruction/generate`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function listRuns(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/runs`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function createRun(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/runs`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function getRun(baseUrl: string, pathParams: { run_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/runs/${encodeURIComponent(pathParams.run_id)}`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function submitRunOtp(baseUrl: string, pathParams: { run_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/runs/${encodeURIComponent(pathParams.run_id)}/otp`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function cancelRun(baseUrl: string, pathParams: { run_id: string }, init?: RequestInit): Promise<unknown> {
  const path = `/api/runs/${encodeURIComponent(pathParams.run_id)}/cancel`;
  return requestJson(baseUrl, path, "POST", init);
}

export async function getVonageInboundSms(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/integrations/vonage/inbound-sms`;
  return requestJson(baseUrl, path, "GET", init);
}

export async function postVonageInboundSms(baseUrl: string, init?: RequestInit): Promise<unknown> {
  const path = `/api/integrations/vonage/inbound-sms`;
  return requestJson(baseUrl, path, "POST", init);
}



export const AUTOMATION_API_OPERATIONS = [
  {
    "operationId": "getCsrfToken",
    "method": "GET",
    "path": "/api/csrf"
  },
  {
    "operationId": "postRegisterUser",
    "method": "POST",
    "path": "/api/register"
  },
  {
    "operationId": "listAutomationCommands",
    "method": "GET",
    "path": "/api/automation/commands"
  },
  {
    "operationId": "listAutomationTasks",
    "method": "GET",
    "path": "/api/automation/tasks"
  },
  {
    "operationId": "getAutomationTask",
    "method": "GET",
    "path": "/api/automation/tasks/{task_id}"
  },
  {
    "operationId": "runAutomationCommand",
    "method": "POST",
    "path": "/api/automation/run"
  },
  {
    "operationId": "cancelAutomationTask",
    "method": "POST",
    "path": "/api/automation/tasks/{task_id}/cancel"
  },
  {
    "operationId": "createComputerUseSession",
    "method": "POST",
    "path": "/api/computer-use/sessions"
  },
  {
    "operationId": "previewComputerUseAction",
    "method": "POST",
    "path": "/api/computer-use/sessions/{session_id}/preview"
  },
  {
    "operationId": "confirmComputerUseAction",
    "method": "POST",
    "path": "/api/computer-use/sessions/{session_id}/confirm/{action_id}"
  },
  {
    "operationId": "executeComputerUseAction",
    "method": "POST",
    "path": "/api/computer-use/sessions/{session_id}/execute/{action_id}"
  },
  {
    "operationId": "readComputerUseEvidence",
    "method": "GET",
    "path": "/api/computer-use/sessions/{session_id}/evidence"
  },
  {
    "operationId": "createBatchEmbeddings",
    "method": "POST",
    "path": "/api/embeddings/batch"
  },
  {
    "operationId": "listSessions",
    "method": "GET",
    "path": "/api/sessions"
  },
  {
    "operationId": "startSession",
    "method": "POST",
    "path": "/api/sessions/start"
  },
  {
    "operationId": "finishSession",
    "method": "POST",
    "path": "/api/sessions/{session_id}/finish"
  },
  {
    "operationId": "listFlows",
    "method": "GET",
    "path": "/api/flows"
  },
  {
    "operationId": "createFlow",
    "method": "POST",
    "path": "/api/flows"
  },
  {
    "operationId": "importLatestFlow",
    "method": "POST",
    "path": "/api/flows/import-latest"
  },
  {
    "operationId": "getFlow",
    "method": "GET",
    "path": "/api/flows/{flow_id}"
  },
  {
    "operationId": "patchFlow",
    "method": "PATCH",
    "path": "/api/flows/{flow_id}"
  },
  {
    "operationId": "listTemplates",
    "method": "GET",
    "path": "/api/templates"
  },
  {
    "operationId": "createTemplate",
    "method": "POST",
    "path": "/api/templates"
  },
  {
    "operationId": "postTemplatesFromArtifacts",
    "method": "POST",
    "path": "/api/templates/from-artifacts"
  },
  {
    "operationId": "getTemplate",
    "method": "GET",
    "path": "/api/templates/{template_id}"
  },
  {
    "operationId": "patchTemplate",
    "method": "PATCH",
    "path": "/api/templates/{template_id}"
  },
  {
    "operationId": "exportTemplate",
    "method": "GET",
    "path": "/api/templates/{template_id}/export"
  },
  {
    "operationId": "resolveProfile",
    "method": "POST",
    "path": "/api/profiles/resolve"
  },
  {
    "operationId": "previewReconstruction",
    "method": "POST",
    "path": "/api/reconstruction/preview"
  },
  {
    "operationId": "generateReconstruction",
    "method": "POST",
    "path": "/api/reconstruction/generate"
  },
  {
    "operationId": "listRuns",
    "method": "GET",
    "path": "/api/runs"
  },
  {
    "operationId": "createRun",
    "method": "POST",
    "path": "/api/runs"
  },
  {
    "operationId": "getRun",
    "method": "GET",
    "path": "/api/runs/{run_id}"
  },
  {
    "operationId": "submitRunOtp",
    "method": "POST",
    "path": "/api/runs/{run_id}/otp"
  },
  {
    "operationId": "cancelRun",
    "method": "POST",
    "path": "/api/runs/{run_id}/cancel"
  },
  {
    "operationId": "getVonageInboundSms",
    "method": "GET",
    "path": "/api/integrations/vonage/inbound-sms"
  },
  {
    "operationId": "postVonageInboundSms",
    "method": "POST",
    "path": "/api/integrations/vonage/inbound-sms"
  }
] as const;

